# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.CharField(max_length=120)),
                ('app', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('uniqueid', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=120)),
                ('email_password', models.CharField(max_length=120)),
                ('fbOath', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='connectiondetail',
            name='uniqueid',
            field=models.ForeignKey(max_length=120, on_delete=django.db.models.deletion.CASCADE, to='rango.UserInformation'),
        ),
    ]
